//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_AppCMC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model_CMCBacNinhEntities : DbContext
    {
        public Model_CMCBacNinhEntities()
            : base("name=Model_CMCBacNinhEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblDieuPhoiTrangThaiVC> tblDieuPhoiTrangThaiVCs { get; set; }
        public virtual DbSet<tblDieuPhoiVanChuyen> tblDieuPhoiVanChuyens { get; set; }
        public virtual DbSet<tblDMDoor> tblDMDoors { get; set; }
        public virtual DbSet<tblDMHangHoa> tblDMHangHoas { get; set; }
        public virtual DbSet<tblNhanSu> tblNhanSus { get; set; }
        public virtual DbSet<tblSysUser> tblSysUsers { get; set; }
    }
}
