//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_AppCMC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDieuPhoiVanChuyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDieuPhoiVanChuyen()
        {
            this.tblDieuPhoiTrangThaiVCs = new HashSet<tblDieuPhoiTrangThaiVC>();
        }
    
        public long ID { get; set; }
        public string CodeChuyen { get; set; }
        public Nullable<System.DateTime> NgayDongHang { get; set; }
        public Nullable<System.DateTime> NgayTraHang { get; set; }
        public Nullable<long> IDDiemDi { get; set; }
        public Nullable<long> IDDiemDen { get; set; }
        public Nullable<double> SoPL { get; set; }
        public Nullable<double> SoKhoi { get; set; }
        public Nullable<double> SoKG { get; set; }
        public Nullable<long> IDDMXeOto { get; set; }
        public Nullable<long> IDLaiXe { get; set; }
        public Nullable<long> IDCreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> STT { get; set; }
        public Nullable<int> EnumThueXeOrXeMinh { get; set; }
        public string BienSoXe { get; set; }
        public string LaiXe { get; set; }
        public string DTLaiXe { get; set; }
        public Nullable<long> IDDMCustomerTranport { get; set; }
        public Nullable<long> IDDMCustomer { get; set; }
        public Nullable<long> IDDMHangHoa { get; set; }
        public Nullable<bool> FlagHangVe { get; set; }
        public Nullable<System.DateTime> ThoiGianVe { get; set; }
        public Nullable<long> SoGioCho { get; set; }
        public Nullable<long> SoCaLuu { get; set; }
        public string CodeDieuVan { get; set; }
        public Nullable<long> IDDMLoaiXe { get; set; }
        public Nullable<int> EnumTrangThaiDieuPhoi { get; set; }
        public Nullable<bool> FlagDaDieuPhoi { get; set; }
        public string GhiChu { get; set; }
        public Nullable<long> IDUserDieuPhoi { get; set; }
        public Nullable<long> IDTrangThaiVanChuyen { get; set; }
        public Nullable<int> STTDieuPhoi { get; set; }
        public Nullable<long> VeBenBai { get; set; }
        public string PhatSinhKhac { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDieuPhoiTrangThaiVC> tblDieuPhoiTrangThaiVCs { get; set; }
        public virtual tblSysUser tblSysUser { get; set; }
        public virtual tblDMDoor tblDMDoor { get; set; }
        public virtual tblDMDoor tblDMDoor1 { get; set; }
        public virtual tblDMHangHoa tblDMHangHoa { get; set; }
        public virtual tblNhanSu tblNhanSu { get; set; }
        public virtual tblSysUser tblSysUser1 { get; set; }
    }
}
