//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_AppCMC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDMHangHoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDMHangHoa()
        {
            this.tblDieuPhoiVanChuyens = new HashSet<tblDieuPhoiVanChuyen>();
        }
    
        public long ID { get; set; }
        public string NameVI { get; set; }
        public string NameEN { get; set; }
        public string Code { get; set; }
        public Nullable<bool> FlagFavorite { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDieuPhoiVanChuyen> tblDieuPhoiVanChuyens { get; set; }
    }
}
