//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_AppCMC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDieuPhoiTrangThaiVC
    {
        public long ID { get; set; }
        public Nullable<long> IDDieuPhoi { get; set; }
        public Nullable<long> IDDMTrangThaiVanChuyen { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<long> IDUserCreate { get; set; }
        public Nullable<System.DateTime> NgayGioThucHien { get; set; }
        public string NoiDung { get; set; }
    
        public virtual tblDieuPhoiVanChuyen tblDieuPhoiVanChuyen { get; set; }
        public virtual tblSysUser tblSysUser { get; set; }
    }
}
