//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_AppCMC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDMDoor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDMDoor()
        {
            this.tblDieuPhoiVanChuyens = new HashSet<tblDieuPhoiVanChuyen>();
            this.tblDieuPhoiVanChuyens1 = new HashSet<tblDieuPhoiVanChuyen>();
        }
    
        public long ID { get; set; }
        public Nullable<int> EnumTypeOfDoor { get; set; }
        public Nullable<long> IDQuocGia { get; set; }
        public Nullable<long> IDCity { get; set; }
        public string Code { get; set; }
        public string NameVI { get; set; }
        public string NameEN { get; set; }
        public string AddressVI { get; set; }
        public string AddressEN { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Note { get; set; }
        public string TaxCode { get; set; }
        public Nullable<double> MaxMoneyDebit { get; set; }
        public Nullable<int> PaymentPeriod { get; set; }
        public Nullable<bool> FlagFavorite { get; set; }
        public Nullable<long> IDBank { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankBranchName { get; set; }
        public string BankAddress { get; set; }
        public Nullable<double> SoDuVND { get; set; }
        public Nullable<double> SoDuUSD { get; set; }
        public Nullable<double> PhanTramPhaiThuChi { get; set; }
        public Nullable<long> IDCustomer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDieuPhoiVanChuyen> tblDieuPhoiVanChuyens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDieuPhoiVanChuyen> tblDieuPhoiVanChuyens1 { get; set; }
    }
}
