//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_AppCMC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSysUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSysUser()
        {
            this.tblDieuPhoiTrangThaiVCs = new HashSet<tblDieuPhoiTrangThaiVC>();
            this.tblDieuPhoiVanChuyens = new HashSet<tblDieuPhoiVanChuyen>();
            this.tblDieuPhoiVanChuyens1 = new HashSet<tblDieuPhoiVanChuyen>();
        }
    
        public long ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<long> IDNhanVien { get; set; }
        public Nullable<long> IDGroupUser { get; set; }
        public Nullable<bool> Active { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> Fixed { get; set; }
        public string Permission { get; set; }
        public Nullable<bool> StatusLogin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDieuPhoiTrangThaiVC> tblDieuPhoiTrangThaiVCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDieuPhoiVanChuyen> tblDieuPhoiVanChuyens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDieuPhoiVanChuyen> tblDieuPhoiVanChuyens1 { get; set; }
        public virtual tblNhanSu tblNhanSu { get; set; }
    }
}
